name: Build 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 20 * * *'

jobs:

  build:

    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 3la-docker:$(date +%s)
