# This workflow builds the Docker image on pipsqueak.
name: Build and test on self-hosted

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 20 * * *'

jobs:

  cleaner:
    runs-on: self-hosted
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"

  build-and-test:
    # Make sure we clean up the directory first. The runner does not remove
    # files from old runs.
    needs: cleaner
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.PAT }}

    - name: Build the Docker image
      id: build
      run: |
        export TAG=3la-docker:$(date +%s)
        echo "::set-output name=TAG::$TAG"
        DOCKER_BUILDKIT=1 docker build \
          . \
          --file Dockerfile \
          --build-arg=TVM_BUILD_JOBS=16 \
          --ssh default \
          --no-cache \
          --tag $TAG
    - name: Run tests
      run: docker run ${{ steps.build.outputs.TAG }} ./run.sh
