name: Build 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 20 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build --ssh --file Dockerfile --tag 3la-docker:$(date +%s) .
