name: Build and test on GitHub runners

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 20 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_KEY }}
    - name: Build the Docker image
      id: build
      run: |
        export TAG=3la-docker:$(date +%s)
        echo "::set-output name=TAG::$TAG"
        docker build \
          . \
          --file Dockerfile \
          --no-cache \
          --tag $TAG
    - name: Run tests
      run: docker run ${{ steps.build.outputs.TAG }} cargo test --no-default-features --features "tvm run-on-github-actions"