# This workflow builds the Docker image on pipsqueak.
name: Build and test on self-hosted

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 20 * * *'

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --ssh default --no-cache --file Dockerfile --tag 3la-docker:$(date +%s)
